Fix panic when MML portamento has less than 2 notes
No need to update the changelog.  The bug was added after v0.0.14
in commit 3a715456f46717851fa0ac306181ad35c37b8a81 (2024-12-11).

    ---- portamento_panic_bugfix stdout ----
    thread 'portamento_panic_bugfix' panicked at crates/compiler/src/mml/command_parser.rs:1465:21:
    index out of bounds: the len is 1 but the index is 1
    stack backtrace:
       0: rust_begin_unwind
       1: core::panicking::panic_fmt
       2: core::panicking::panic_bounds_check
       3: <usize as core::slice::index::SliceIndex<[T]>>::index
                 at /usr/src/debug/rust/rustc-1.83.0-src/library/core/src/slice/index.rs:301:10
       4: core::slice::index::<impl core::ops::index::Index<I> for [T]>::index
                 at /usr/src/debug/rust/rustc-1.83.0-src/library/core/src/slice/index.rs:16:9
       5: <alloc::vec::Vec<T,A> as core::ops::index::Index<I>>::index
                 at /usr/src/debug/rust/rustc-1.83.0-src/library/alloc/src/vec/mod.rs:3323:9
       6: compiler::mml::command_parser::parse_portamento
                 at ./src/mml/command_parser.rs:1465:21