Fix missing set_detune 0 instruction when MD value is small
    ---- test_small_detune_cents stdout ----
    thread 'test_small_detune_cents' panicked at crates/compiler/tests/mml.rs:6940:5:
    assertion `left == right` failed: Testing "MD+1 o4 c o2 d e o3 f" against bytecode
      left: [10, 0, 22, 1, 161, 23, 117, 23, 121, 23, 147, 23, 63]
     right: [10, 0, 22, 1, 161, 23, 22, 0, 117, 23, 121, 23, 22, 1, 147, 23, 63]