Fix missing error on subroutine tail call recursion
    thread 'subroutines::tail_call_recursion_error' (64648) panicked at crates/compiler/tests/mml/main.rs:470:9:
    expected a single CannotCallSubroutineRecursion("s") error on !s, line_char 6
    Input: "\n!s r !s\nA !s\n"
    Result: Ok(SongData)