Fix github actions build failure
    thread 'main' (5238) panicked at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/alsa-sys-0.4.0/build.rs:13:19:

    pkg-config exited with status code 1
    > PKG_CONFIG_ALLOW_SYSTEM_LIBS=1 PKG_CONFIG_ALLOW_SYSTEM_CFLAGS=1 pkg-config --libs --cflags alsa

    The system library `alsa` required by crate `alsa-sys` was not found.
    The file `alsa.pc` needs to be installed and the PKG_CONFIG_PATH environment variable must contain its parent directory.
    The PKG_CONFIG_PATH environment variable is not set.

    HINT: if you have installed the library, try setting PKG_CONFIG_PATH to the directory containing `alsa.pc`.