Fix RingBuffer is full panic in the audio thread
I forgot to fill the ring buffer before starting playback.

This panic occurs 35% of the time on a debug build (after 20 tests).
I did not encounter a panic on the release build.

    thread 'audio_thread' panicked at crates/tad-gui/src/audio_thread.rs:91:13:
    RingBuffer is full
    stack backtrace:
       0: rust_begin_unwind
                 at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:595:5
       1: core::panicking::panic_fmt
                 at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/panicking.rs:67:14
       2: tad_gui::audio_thread::RingBuffer::add_chunk
                 at ./crates/tad-gui/src/audio_thread.rs:91:13
       3: tad_gui::audio_thread::fill_ring_buffer
                 at ./crates/tad-gui/src/audio_thread.rs:161:20
       4: tad_gui::audio_thread::audio_thread
                 at ./crates/tad-gui/src/audio_thread.rs:289:25
       5: tad_gui::audio_thread::create_audio_thread::{{closure}}
                 at ./crates/tad-gui/src/audio_thread.rs:381:21
    note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.