Fix hint in song-loop panic in L song-loop command
The panic was caused by the song channel's instrument_state being
erroneously set to InstrumentState::Hint when calling a subroutine with
an instrument-hint with no instrument set.

    thread 'instruments_and_envelope::instrument_hint_and_song_loop_panic_bugfix' panicked at crates/compiler/src/bytecode.rs:756:31:
    hint in song-loop
    stack backtrace:
       0: rust_begin_unwind
                 at /rustc/9fc6b43126469e3858e2fe86cafb4f0fd5068869/library/std/src/panicking.rs:665:5
       1: core::panicking::panic_fmt
                 at /rustc/9fc6b43126469e3858e2fe86cafb4f0fd5068869/library/core/src/panicking.rs:76:14
       2: compiler::bytecode::InstrumentState::demote_to_song_loop
                 at ./src/bytecode.rs:756:31
       3: compiler::bytecode::State::song_loop
                 at ./src/bytecode.rs:1013:9
       4: compiler::bytecode::Bytecode::_song_loop_point
                 at ./src/bytecode.rs:1248:9
       5: compiler::channel_bc_generator::ChannelBcGenerator::process_command
                 at ./src/channel_bc_generator.rs:1542:21