Fixed wav2brr unable to parse --loop-point or --dupe-block-hack arguments
Reported by Zathrontria

    > cargo run --bin wav2brr -- -l 32 -o /tmp/test.brr examples/samples/sine.wav
        Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.04s
         Running `target/debug/wav2brr -l 32 -o /tmp/test.brr examples/samples/sine.wav`

    thread 'main' (50248) panicked at crates/wav2brr/src/main.rs:61:17:
    Mismatch between definition and access of `loop_point`. Could not downcast to brr::SampleNumber, need to downcast to usize

    > cargo run --bin wav2brr -- --dupe-block-hack 2 -o /tmp/test.brr examples/samples/sine.wav
        Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.04s
         Running `target/debug/wav2brr --dupe-block-hack 2 -o /tmp/test.brr examples/samples/sine.wav`

    thread 'main' (55427) panicked at crates/wav2brr/src/main.rs:70:22:
    Mismatch between definition and access of `dupe_block_hack`. Could not downcast to brr::BlockNumber, need to downcast to usize