Fix portamento note tracking bug that can cause portamento to not key-on
The note tracking bug erroneously dropped the `play_note ? no_keyoff ?`
instructions in this test:

    thread 'test_portamento_note_tracking_bugfix_1' panicked at crates/compiler/tests/mml.rs:6013:5:
    assertion `left == right` failed: Testing "{cd} {cf} {cg}" against bytecode
      left: [8, 0, 160, 1, 1, 12, 22, 165, 1, 31, 23, 171, 1, 46, 23, 175, 63]
     right: [8, 0, 160, 1, 1, 12, 22, 165, 160, 1, 1, 33, 22, 171, 160, 1, 1, 49, 22, 175, 63]
    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

This bug can also cause portamento to emit unnecessary
`play_note ? no_keyoff ?` instructions;

    thread 'test_portamento_note_tracking_bugfix_2' panicked at crates/compiler/tests/mml.rs:6013:5:
    assertion `left == right` failed: Testing "{cd} & {df} & {fg}" against bytecode
      left: [8, 0, 160, 1, 1, 11, 23, 164, 164, 1, 1, 20, 23, 170, 170, 1, 1, 16, 22, 175, 63]
     right: [8, 0, 160, 1, 1, 11, 23, 164, 1, 19, 24, 170, 1, 15, 23, 175, 63]