Fix missing set_instrument if instrument matches subroutine hint
For the `!s ?@1 GF0 {dg} @1 {gd}` test:
    thread 'test_subroutine_instrument_hint_then_set_same_instrument' panicked at crates/compiler/tests/mml.rs:6700:5:
    assertion `left == right` failed
      left: [11, 0, 164, 1, 1, 18, 22, 175, 174, 1, 0, 18, 22, 165, 41]
     right: [11, 0, 164, 1, 1, 18, 22, 175, 8, 5, 174, 1, 0, 18, 22, 165, 41]