Fix portamento not testing if detune was changed after the previous note
    thread 'test_slurred_note_detune_then_portamento' panicked at crates/compiler/tests/mml.rs:7075:5:
    assertion `left == right` failed: Testing "c & D+80 {c g}" against bytecode
      left: [10, 0, 160, 24, 22, 80, 1, 175, 46, 23, 63]
     right: [10, 0, 160, 24, 22, 80, 160, 1, 1, 175, 49, 22, 63]