Fix compiler_thread panic after removing an item and then editing the last item
I forgot to decrement the indexes in the ItemId and name maps.

> thread 'compiler_thread' panicked at crates/tad-gui/src/compiler_thread.rs:400:42:
> index out of bounds: the len is 34 but the index is 34
>
> stack backtrace:
>    [...]
>    6: tad_gui::compiler_thread::CList<ItemT,OutT>::add_or_edit
>              at ./crates/tad-gui/src/compiler_thread.rs:400:42