Fix loop analysis assert panic with subroutine self recursion
    thread 'subroutines::self_recursion_loop_analysis_panic_bugfix' (400088) panicked at crates/compiler/src/command_compiler/channel_bc_generator.rs:1652:21:
    assertion `left == right` failed
      left: None
     right: Some(InstrumentId(0))

I have removed the problematic `debug_assert_eq` from the
Command::EndLoop bytecode generator.  There is no easy way to determine
if an instrument_id mismatch is caused by a subroutine compile error or
a code bug.

The command analyser's instrument is still assert-tested against the
bytecode module's instrument tracking after all subroutines have been
compiled.