Fix state tracking after a L set song loop point MML command
This can cause dropped instructions after the L MML command.

    ---- test_envelope_after_song_loop_point_and_loop stdout ----
    thread 'test_envelope_after_song_loop_point_and_loop' panicked at crates/compiler/tests/mml.rs:6828:5:
    assertion `left == right` failed
      left: [9, 0, 0, 80, 161, 23, 165, 23, 34, 2, 169, 23, 39, 171, 23, 38, 247, 255]
     right: [9, 0, 0, 80, 161, 23, 165, 23, 34, 2, 169, 23, 39, 11, 80, 171, 23, 38, 245, 255]

    ---- test_set_instrument_after_song_loop_point_and_loop stdout ----
    thread 'test_set_instrument_after_song_loop_point_and_loop' panicked at crates/compiler/tests/mml.rs:6828:5:
    assertion `left == right` failed
      left: [8, 0, 179, 23, 183, 23, 34, 2, 161, 23, 39, 161, 23, 165, 23, 8, 1, 169, 23, 38, 241, 255]
     right: [8, 0, 179, 23, 183, 23, 34, 2, 161, 23, 39, 8, 0, 161, 23, 165, 23, 8, 1, 169, 23, 38, 239, 255]